exclude: [README.md, resources/src]
title: AmsterdamNLP - Natural Language Processing at the University of Amsterdam
email: zuidema@uva.nl
description: > 
    This is where you will find much about Natural Language Processing in Amsterdam.
url: "//amsterdamNLP.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: amsterdamNLP
paginate: 3

# useful links
illc_url: http://www.illc.uva.nl
uva_url: http://www.uva.nl/en/home

# Build settings
markdown: kramdown

